version: '3.8'

services:
  client:
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - node

  node:
    image: node:20-alpine
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["npm", "install"]
